const fonts = {
  // Poppins font variants
  PoppinsBlack: 'Poppins-Black',
  PoppinsBlackItalic: 'Poppins-BlackItalic',
  PoppinsBold: 'Poppins-Bold',
  PoppinsBoldItalic: 'Poppins-BoldItalic',
  PoppinsExtraBold: 'Poppins-ExtraBold',
  PoppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  PoppinsExtraLight: 'Poppins-ExtraLight',
  PoppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
  PoppinsItalic: 'Poppins-Italic',
  PoppinsLight: 'Poppins-Light',
  PoppinsLightItalic: 'Poppins-LightItalic',
  PoppinsMedium: 'Poppins-Medium',
  PoppinsMediumItalic: 'Poppins-MediumItalic',
  PoppinsRegular: 'Poppins-Regular',
  PoppinsSemiBold: 'Poppins-SemiBold',
  PoppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
  PoppinsThin: 'Poppins-Thin',
  PoppinsThinItalic: 'Poppins-ThinItalic',

  // Roboto Condensed font variants
  RobotoCondensedBlack: 'Roboto_Condensed-Black',
  RobotoCondensedBlackItalic: 'Roboto_Condensed-BlackItalic',
  RobotoCondensedBold: 'Roboto_Condensed-Bold',
  RobotoCondensedBoldItalic: 'Roboto_Condensed-BoldItalic',
  RobotoCondensedExtraBold: 'Roboto_Condensed-ExtraBold',
  RobotoCondensedExtraBoldItalic: 'Roboto_Condensed-ExtraBoldItalic',
  RobotoCondensedExtraLight: 'Roboto_Condensed-ExtraLight',
  RobotoCondensedExtraLightItalic: 'Roboto_Condensed-ExtraLightItalic',
  RobotoCondensedItalic: 'Roboto_Condensed-Italic',
  RobotoCondensedLight: 'Roboto_Condensed-Light',
  RobotoCondensedLightItalic: 'Roboto_Condensed-LightItalic',
  RobotoCondensedMedium: 'Roboto_Condensed-Medium',
  RobotoCondensedMediumItalic: 'Roboto_Condensed-MediumItalic',
  RobotoCondensedRegular: 'Roboto_Condensed-Regular',
  RobotoCondensedSemiBold: 'Roboto_Condensed-SemiBold',
  RobotoCondensedSemiBoldItalic: 'Roboto_Condensed-SemiBoldItalic',
  RobotoCondensedThin: 'Roboto_Condensed-Thin',
  RobotoCondensedThinItalic: 'Roboto_Condensed-ThinItalic',

  // Roboto SemiCondensed font variants
  RobotoSemiCondensedBlack: 'Roboto_SemiCondensed-Black',
  RobotoSemiCondensedBlackItalic: 'Roboto_SemiCondensed-BlackItalic',
  RobotoSemiCondensedBold: 'Roboto_SemiCondensed-Bold',
  RobotoSemiCondensedBoldItalic: 'Roboto_SemiCondensed-BoldItalic',
  RobotoSemiCondensedExtraBold: 'Roboto_SemiCondensed-ExtraBold',
  RobotoSemiCondensedExtraBoldItalic: 'Roboto_SemiCondensed-ExtraBoldItalic',
  RobotoSemiCondensedExtraLight: 'Roboto_SemiCondensed-ExtraLight',
  RobotoSemiCondensedExtraLightItalic: 'Roboto_SemiCondensed-ExtraLightItalic',
  RobotoSemiCondensedItalic: 'Roboto_SemiCondensed-Italic',
  RobotoSemiCondensedLight: 'Roboto_SemiCondensed-Light',
  RobotoSemiCondensedLightItalic: 'Roboto_SemiCondensed-LightItalic',
  RobotoSemiCondensedMedium: 'Roboto_SemiCondensed-Medium',
  RobotoSemiCondensedMediumItalic: 'Roboto_SemiCondensed-MediumItalic',
  RobotoSemiCondensedRegular: 'Roboto_SemiCondensed-Regular',
  RobotoSemiCondensedSemiBold: 'Roboto_SemiCondensed-SemiBold',
  RobotoSemiCondensedSemiBoldItalic: 'Roboto_SemiCondensed-SemiBoldItalic',
  RobotoSemiCondensedThin: 'Roboto_SemiCondensed-Thin',
  RobotoSemiCondensedThinItalic: 'Roboto_SemiCondensed-ThinItalic',

  // Roboto font variants
  RobotoBlack: 'Roboto-Black',
  RobotoBlackItalic: 'Roboto-BlackItalic',
  RobotoBold: 'Roboto-Bold',
  RobotoBoldItalic: 'Roboto-BoldItalic',
  RobotoExtraBold: 'Roboto-ExtraBold',
  RobotoExtraBoldItalic: 'Roboto-ExtraBoldItalic',
  RobotoExtraLight: 'Roboto-ExtraLight',
  RobotoExtraLightItalic: 'Roboto-ExtraLightItalic',
  RobotoItalic: 'Roboto-Italic',
  RobotoLight: 'Roboto-Light',
  RobotoLightItalic: 'Roboto-LightItalic',
  RobotoMedium: 'Roboto-Medium',
  RobotoMediumItalic: 'Roboto-MediumItalic',
  RobotoRegular: 'Roboto-Regular',
  RobotoSemiBold: 'Roboto-SemiBold',
  RobotoSemiBoldItalic: 'Roboto-SemiBoldItalic',
  RobotoThin: 'Roboto-Thin',
  RobotoThinItalic: 'Roboto-ThinItalic',
  RobotoVariable: 'Roboto-VariableFont_wdth,wght',
};

export default fonts;
